---
# 完整的 PowerDNS + cert-manager + ZeroSSL 泛域名证书自动化方案
#
# 使用方法:
# 1. 获取 ZeroSSL EAB 凭证: https://app.zerossl.com/developer
# 2. 设置环境变量:
#    export ZEROSSL_EAB_KID=your_eab_kid
#    export ZEROSSL_EAB_HMAC_KEY=your_eab_hmac_key
# 3. 部署:
#    envsubst < zerossl-powerdns-auto.yaml | kubectl apply -f -
#
# 步骤 1: 安装 cert-manager
# kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.14.0/cert-manager.yaml

# 步骤 2: 安装 cert-manager-webhook-powerdns
# export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
# helm repo add cert-manager-webhook-powerdns https://zachomedia.github.io/cert-manager-webhook-pdns
# helm repo update
# helm install cert-manager-webhook-powerdns cert-manager-webhook-powerdns/cert-manager-webhook-pdns -n cert-manager

---
# ZeroSSL EAB Secret
apiVersion: v1
kind: Secret
metadata:
  name: zerossl-eab
  namespace: cert-manager
type: Opaque
stringData:
  secret: ${ZEROSSL_EAB_HMAC_KEY}

---
# PowerDNS API Secret
apiVersion: v1
kind: Secret
metadata:
  name: powerdns-api-key
  namespace: cert-manager
type: Opaque
stringData:
  api-key: "changeme-api-key"  # 与 PowerDNS 配置中的 api-key 一致

---
# ZeroSSL ACME Issuer - 使用 PowerDNS Webhook
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl-powerdns
spec:
  acme:
    server: https://acme.zerossl.com/v2/DV90
    email: shadowsocks1984@gmail.com

    privateKeySecretRef:
      name: zerossl-account-key

    externalAccountBinding:
      keyID: ${ZEROSSL_EAB_KID}
      keySecretRef:
        name: zerossl-eab
        key: secret

    solvers:
    - dns01:
        webhook:
          groupName: acme.zacharyseguin.ca
          solverName: pdns
          config:
            # PowerDNS API 配置
            host: http://powerdns-api.powerdns-system.svc.cluster.local:8081
            apiKeySecretRef:
              name: powerdns-api-key
              key: api-key
            # PowerDNS 服务器 ID（通常是 localhost）
            serverID: localhost
            # TTL 设置
            ttl: 120

---
# 申请泛域名证书
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mesh-worker-wildcard
  namespace: ingress
spec:
  secretName: mesh-worker-wildcard-tls
  issuerRef:
    name: zerossl-powerdns
    kind: ClusterIssuer
  dnsNames:
  - "mesh-worker.com"
  - "*.mesh-worker.com"
  renewBefore: 720h  # 30天前自动续期

---
# 使用证书的 Traefik IngressRoute - 泛域名路由到 control-plane-outer
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mesh-worker-wildcard-https
  namespace: ingress
spec:
  entryPoints:
    - websecure  # HTTPS 入口
  routes:
  - match: HostRegexp(`{subdomain:[a-z0-9-]+}.mesh-worker.com`) || Host(`mesh-worker.com`)
    kind: Rule
    services:
    - name: control-plane-outer
      namespace: console
      port: 9900
  tls:
    secretName: mesh-worker-wildcard-tls  # 使用 ZeroSSL 泛域名证书

